# Generated by Django 5.0.7 on 2024-08-17 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bus", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rating",
            name="booking",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="Bus.booking"
            ),
        ),
    ]
