# Generated by Django 5.0.7 on 2024-08-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bus", "0002_rating_booking"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="arrival_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="starting_time",
            field=models.DateTimeField(null=True),
        ),
    ]
