# Generated by Django 5.0.7 on 2024-08-17 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Bus", "0003_booking_arrival_time_booking_starting_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rating",
            name="rating",
        ),
    ]
